# -*- coding: utf-8 -*-
"""Flask_deploy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wvDv7pmOfJIZ5X3bx8KICv1Isn-MPdhE
"""

from sklearn import svm
from sklearn import datasets
clf = svm.SVC(gamma='scale')
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf.fit(X, y)  





import pickle
pickle.dump(clf, open('model.pkl','wb'))
